spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(M6LbdxGRILwNyPxfFZTbMXtPxpo2hFB9kkQNvcPTTYS2oXZJZB9BivAzM++oGMkT)
    username: ENC(YmQW5xDNLxPHhYQ5e5t15Q==)
    password: ENC(3Se4j0PMDxBJAKqfhdfKsg==)
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true