spring:
  application:
    name: ticket-server
  jpa:
    open-in-view: false
  flyway:
    enabled: false
    baseline-on-migrate: false

cors:
  allowed:
    api: /api/**
    origins:
      - http://localhost:3000
      - http://127.0.0.1:3000
    methods: '*'